import { GoogleGenAI, Modality } from "@google/genai";
import { ModificationOptions } from "../types";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = async (file: File) => {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
    reader.readAsDataURL(file);
  });
  return {
    inlineData: { data: await base64EncodedDataPromise, mimeType: file.type },
  };
};

export const generateImage = async (
  imageFile: File,
  options: ModificationOptions
): Promise<string> => {
  try {
    const model = 'gemini-2.5-flash-image';
    const imagePart = await fileToGenerativePart(imageFile);

    const promptLines = [
      'For the provided image, generate a new high-quality, photorealistic image with the following modifications.',
      'The new image should be suitable for an advertisement.',
      `- Time of Day: ${options.timeOfDay}.`,
      `- Season: ${options.season}.`,
      `- Tourists: ${options.tourists}.`,
      `- Perspective: ${options.perspective}.`
    ];

    if (options.removeText) {
      promptLines.push('- Cleanup: Remove ALL watermarks, logos, numbers, and any other text overlays from the image.');
    }

    promptLines.push(`- Aspect Ratio: ${options.format}.`);
    promptLines.push(`- Additional Instructions: ${options.customPrompt || 'None'}.`);
    promptLines.push('Ensure the final image is a cohesive and believable scene based on these requirements.');

    const prompt = promptLines.join('\n');


    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [imagePart, { text: prompt }],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64ImageBytes: string = part.inlineData.data;
          return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
        }
    }

    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error generating image:", error);
    if (error instanceof Error) {
        return Promise.reject(error.message);
    }
    return Promise.reject("An unknown error occurred while generating the image.");
  }
};